image: atlassian/default-image:2

definitions:
  steps:
    - step: &push-docker-image
        name: Push Docker image to ECR
        image: atlassian/pipelines-awscli
        caches:
          - docker
        services:
          - docker
        script:
          # creates variables (timestamp, image name and tag)
          - export TIMESTAMP="$(date +%Y%m%d)"
          - export IMAGE_NAME=application
          - export TAG="$TIMESTAMP"
          # builds docker image from a local dockerfile
          - docker build -t application .
          # tags image as a way to id it by the timestamp
          - docker tag application application:$TIMESTAMP
          # use pipe to push the image to AWS ECR
          - pipe: atlassian/aws-ecr-push-image:1.3.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: us-east-1
              IMAGE_NAME: application:$TIMESTAMP
              TAGS: "$TIMESTAMP $BITBUCKET_BUILD_NUMBER"

    - step: &deploy-nodejs
        name: Deploy NodeJs Service
        script:
          - pipe: atlassian/aws-ecs-deploy:1.6.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: "us-east-1"
              CLUSTER_NAME: "superhero-api"
              SERVICE_NAME: "superhero-api"
              FORCE_NEW_DEPLOYMENT: "true"

pipelines:
  custom:
    nodejs-dev: &nodejs-dev
      - step: *push-docker-image
      - step:
          <<: *deploy-nodejs
          deployment: dev-deploy

  branches:
    dev: *nodejs-dev
