script:
  - pipe: atlassian/aws-ecs-deploy:1.6.1
    variables:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: "us-east-1"
      CLUSTER_NAME: "superher-api"
      SERVICE_NAME: "superhero-api"
      TASK_DEFINITION: "task-definition.json"
