definitions:
  steps:
    - step: &push-docker-image
        name: Push Docker image to ECR
        services:
          - docker
        script:
          # build the image
          - apt-get update && apt-get install -y awscli
          - eval $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 992250665077.dkr.ecr.us-east-1.amazonaws.com)
          - docker build -t superhero-api .
          - export IMAGE_ID=`docker images -q superhero-api`
          - docker tag $IMAGE_ID 992250665077.dkr.ecr.us-east-1.amazonaws.com/superhero-api:latest
          - docker push 992250665077.dkr.ecr.us-east-1.amazonaws.com/superhero-api:latest
    - step: &deploy-nodejs
        name: Deploy NodeJs Service
        script:
          - pipe: atlassian/aws-ecs-deploy:1.6.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              CLUSTER_NAME: $AWS_CLUSTER_NAME
              SERVICE_NAME: $AWS_SERVICE_NAME
              FORCE_NEW_DEPLOYMENT: "true"

pipelines:
  custom:
    nodejs-dev: &nodejs-dev
      - step: *push-docker-image
      - step:
          <<: *deploy-nodejs
          deployment: dev-deploy

  branches:
    dev: *nodejs-dev
