image: atlassian/default-image:2

definitions:
  steps:
    - step: &push-docker-image
        name: Push Docker image to ECR
        services:
          - docker
        script:
          # creates variables (timestamp, image name and tag)
          - export TIMESTAMP="$(date +%Y%m%d)"
          - export IMAGE_NAME=superhero-api
          - export TAG="$TIMESTAMP"
          # builds docker image from a local dockerfile
          - docker build -t superhero-api .
          # tags image as a way to id it by the timestamp
          - docker tag superhero-api:latest 992250665077.dkr.ecr.us-east-1.amazonaws.com/superhero-api:latest
          - docker push 992250665077.dkr.ecr.us-east-1.amazonaws.com/superhero-api:latest
    - step: &deploy-nodejs
        name: Deploy NodeJs Service
        script:
          - pipe: atlassian/aws-ecs-deploy:1.6.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: "us-east-1"
              CLUSTER_NAME: "superhero-api"
              SERVICE_NAME: "superhero-api"
              FORCE_NEW_DEPLOYMENT: "true"

pipelines:
  custom:
    nodejs-dev: &nodejs-dev
      - step: *push-docker-image
      - step:
          <<: *deploy-nodejs
          deployment: dev-deploy

  branches:
    dev: *nodejs-dev
