definitions:
  steps:
    - step: &push-docker-image
        name: Push Docker image to ECR
        services:
          - docker
        script:
          - pipe: atlassian/aws-ecr-push-image:1.5.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              IMAGE_NAME: "superhero-api"
              TAGS: "latest" # Optional
    - step: &deploy-nodejs
        name: Deploy NodeJs Service
        script:
          - pipe: atlassian/aws-ecs-deploy:1.6.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              CLUSTER_NAME: $AWS_CLUSTER_NAME
              SERVICE_NAME: $AWS_SERVICE_NAME
              FORCE_NEW_DEPLOYMENT: "true"

pipelines:
  custom:
    nodejs-dev: &nodejs-dev
      - step:
          <<: *push-docker-image
          deployment: dev-deploy
      - step:
          <<: *deploy-nodejs
          deployment: dev-deploy

  branches:
    dev: *nodejs-dev
