image: atlassian/default-image:2

definitions:
  steps:
    - step: &push-and-deploy
        name: Push Docker image to ECR and deploy
        services:
          - docker
        script:
          - docker build -t superhero-api .
          - pipe: atlassian/aws-ecr-push-image:1.5.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              IMAGE_NAME: "superhero-api:latest"
              TAGS: "${BITBUCKET_COMMIT} latest"
          - pipe: atlassian/aws-ecs-deploy:1.6.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              CLUSTER_NAME: $AWS_CLUSTER_NAME
              SERVICE_NAME: $AWS_SERVICE_NAME
              FORCE_NEW_DEPLOYMENT: "true"
              TASK_DEFINITION: "task-definition.json"
              DEBUG: "true"
              WAIT: "true"
pipelines:
  custom:
    nodejs-dev: &nodejs-dev
      - step:
          <<: *push-and-deploy
          deployment: dev

  branches:
    dev: *nodejs-dev
