version: "3.1"
services:
  api:
    container_name: superhero-api
    image: superhero-api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT}
    networks:
      - ws-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - psql-db
    restart: unless-stopped
networks:
  ws-network:
    driver: bridge
